# Generated by Django 2.2.4 on 2021-08-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeprofile',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
