# Generated by Django 2.2.4 on 2021-08-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='foruser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='for_users_messages', to='user_dashboard.User'),
            preserve_default=False,
        ),
    ]
